language: python
fast_finish: true

python:
  - 3.6

os:
  - linux
  
notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

before_install:
    - pip -q install coveralls
    # temporary for pip < 9.1
    - pip -q install numpy

install:
    - pip -q install -e .

script: coverage run tests/test.py -v

after_success: coveralls

